name: Build SDK to Maven Local

on:
  push:
    branches: [ main ]
    paths:
      - 'sdk/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Build SDK
        run: ./gradlew clean build

      - name: Publish SDK to Maven Local
        run: ./gradlew :sdk:publishReleasePublicationToMavenLocal
